### ISSUE TITLE
CORB2 jar not working for encryption/decryption on RHEL7

### ISSUE THREAD

**Issue by rskainth82** [marklogic-community/corb2#64]
Hi CORB2 team,

We are using CORB2 version 2.2.0 in our application and recently encountered an issue, where its not working for us when we tried to run the same application using CORB2 on RHEL7. The issue is primarily happening while trying to encryp/decrypt host endpoints, before calling the CORB2 main command to kick off the main process. This encrypt/decrypt process is working perfectly fine in the same application on RHEL6.

Upon further researching, we found out that internally Java code(HostKeyDecrypter) present in CORB2 jar, that performs encryption of host endpoints, is using a command called LSHAL as shown below, which is not working as expected as HAL library is deprecated in RHEL7 and is not present. This is blocking us to run our application using CORB2 on RHEL7. 

Please let us know , how can we resolve this issue? Is there a new CORB2 jar, which has already addressed this issue. As far as we know, even the most recent 2.3.2 CORB2 jar available on GitHub is also having the same issue. Do you know of any other customer who has encountered the same issue and how was it resolved by them?

private static byte[] getLinuxSN()
{
String line = null;
String marker = "system.hardware.serial";
BufferedReader br = null;
try
{
br = read("lshal");
while ((line = br.readLine()) != null) {
if (line.indexOf(marker) != -1)
{
String sn = line.split(marker)[1].trim();
return sn.getBytes();
}
}
throw new IllegalStateException("Unable to find serial number on Linux");
} 
br = read("lshal"); 

Thanks,
Rupinder

**Comment by rjkennedy98** [comment]
Hi Rupinder. Which version of the JDK are you using? Also, do you have the Java Cryptography Extensions installed?

**Comment by hansenmc** [comment]
Indeed, `lshal` has intentionally been dropped, since [HAL has been removed in favor of udev in RHEL7](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Migration_Planning_Guide/sect-Red_Hat_Enterprise_Linux-Migration_Planning_Guide-Package_Replacements.html). I'm not seeing any easy alternatives available that do not require elevated privileges.

We might need to change the HostKeyDecrypter implementation for Linux, since it will not be able to use `lshal` to access the BIOS Serial when running on more recent versions of Linux distros. One option might be to avoid making the call to read `lshal`, or catch any exceptions attempting to exec and then generate the private key without the BIOS Serial, as is currently done for the "other" OSType.

Two hacks that you could immediately apply to temporarily get around this issue when running the current version of CORB with RHEL7:

1. Explicitly set a System Property to assert a different `os.name` value that does not contain "win", "mac", "darwin", "nix", "nux" or "aix", so that the "other" [OSType.getSN()](https://github.com/marklogic/corb2/blob/master/src/main/java/com/marklogic/developer/corb/HostKeyDecrypter.java#L175) method is applied, which will use a static value for the serial number: 

    ```
    java -Dos.name=RHEL7_HACK -cp marklogic-corb-2.3.2.jar com.marklogic.developer.corb.HostKeyDecrypter encrypt secretValue
   ```

2. Create a shell script with the filename "lshal" that returns a line of text starts with "system.hardware.serial" and then the value of the systems serial(or whatever identifier value you want to use). Ensure that this shell script on your path (e.g. put it in /usr/bin/, or set the PATH to include the directory where this shell script lives prior to invoking the Java process), then when the Java process attempts to exec "lshal", it would invoke the shell script and return the serial for the host.

Of course, CORB also provides both the JasyptDecrypter and PrivateKeyDecrypter classes, and it is also possible to configure a custom Decrypter class in which you could generate the private key differently.
