### ISSUE TITLE
Syntax not available for the commands that can be entered in the Command File.

### ISSUE THREAD

**Issue by GolaganiMohan** [marklogic-community/corb2#67]
The syntax is not available for the commands that can be used in the command file. For example: The command 'PAUSE' wouldn't work unless you specify it as 'COMMAND=PAUSE'. I do not know the syntax for the thread count. Should it be 'COMMAND=THREADCOUNT64' or 'COMMAND=THREAD COUNT 64'.

**Comment by mpheckel** [comment]
Try

THREAD-COUNT=64
________________________________

**Comment by GolaganiMohan** [comment]
Thanks Matt. THREAD-COUNT=64 Worked like a charm. But it is good if we have syntax available on the GitHub page.

**Comment by hansenmc** [comment]
Sorry that it was not clear how to use the COMMAND-FILE and the supported options. The COMMAND-FILE is expected to be a standard Java properties file with the relevant CORB options specified as key/value pairs.

When using the command file, two properties can be configured:
- **COMMAND**  the allowable values are: pause, resume, and stop
- **THEAD-COUNT** the value should be a number

For instance:

    COMMAND=pause
    THEAD-COUNT=16

A full list of the CORB properties are listed on the [README ](https://github.com/marklogic-community/corb2#options)with a brief description. Below are the pertinent properties for **COMMAND-FILE**

<table>
<tr>
<td><strong>COMMAND-FILE</strong></td>
<td>A properties file used to configure <strong>COMMAND</strong> and <strong>THREAD-COUNT</strong> while CoRB2 is running. For instance, to temporarily pause execution, or to lower the number of threads in order to throttle execution.</td>
</tr>
<tr>
<td><strong>COMMAND</strong></td>
<td>Pause, resume, and stop the execution of CoRB2. Possible commands include: PAUSE, RESUME, and STOP. If the <strong>COMMAND-FILE</strong> is modified and either there is no <strong>COMMAND</strong> or an invalid value is specified, then execution will RESUME.</td>
</tr>
<tr>
<td><strong>THREAD-COUNT</strong></td>
<td>The number of worker threads. Default is 1.</td>
</tr>
<tr>
<td><strong>COMMAND-FILE-POLL-INTERVAL</strong></td>
<td>Default is 1. The regular interval (seconds) in which the existence of the <strong>COMMAND-FILE</strong> is tested can be controlled by using this property.</td>
</tr>
</table>

There are a number of examples showing how to configure CORB job options in a properties file also in the [README](https://github.com/marklogic-community/corb2#sample-myjobproperties). However, we don't have every possible combination or explicit examples for every option. 

We are planning to flesh out some additional scenarios and will provide better documentation on the CORB GitHub WIKI pages.

**Comment by bbandlamudi** [comment]
PAUSE/RESUME and THREAD-COUNT have been most sought after features in our project, but in almost all the cases, I had to explain how it should be configured and used. I think it would be a good idea to add a small section on how to configure the run time options with a simple example.  FYI - I talked to mohan earlier on this topic.

**Comment by hansenmc** [comment]
@GolaganiMohan could you take a look at the following WIKI page and let me know if it is clear? Any suggestions or feedback are welcome. 

https://github.com/marklogic-community/corb2/wiki/Example:-Using-COMMAND-FILE-to-pause,-resume,-stop-and-change-THREAD-COUNT

We'd like to make it easier for users to understand how to configure CORB jobs and leverage the options and features that are available.

**Comment by GolaganiMohan** [comment]
Thank you.
