### ISSUE TITLE
Connection issue encountered when properties include unexpected values

### ISSUE THREAD

**Issue by kghmanuel** [marklogic-community/corb2#83]
Manifestation:

```
SEVERE: Error initializing CORB
java.lang.IllegalArgumentException: hostname can't be null
```

Cause:
Credentials (XCC-USERNAME and/or XCC-PASSWORD) contains '@'. Other characters may have to be handled as well.

Quote from Bhagat Bandlamudi
> xcc connection is string is put together from individual parts as xcc://username:password@hostname:port/dbname. Since '@' is interpreted as a separator, it probably need to be escaped. I am not sure if we need to force the users to escape it or Corb needs to do it automatically, or at least document it as charactors not allowed.

**Comment by hansenmc** [comment]
When using the **XCC-CONNECTION-URI**, you need to ensure that [reserved characters are properly URLEncoded](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters). 

In the XCC connection string that has the username and password preceding the location, characters such as `:` and `@` are used as delimiters. Similar to why you must URLEncode querystring parameter values that contain `?` or `&` so that there is no confusion about what is a querystring parameter delimiter, the username and password values must be URLEncoded if they contain a reserved character.

So, instead of an XCC connection URI with the password `password@@@`: 
    
    XCC-CONNECTION-URI=xcc://corb:password@@@@localhost:8223/my-content-db

The URLencoded password would be `password%40%40%40`:

    XCC-CONNECTION-URI=xcc://corb:password%40%40%40@localhost:8223/my-content-db

Alternatively, you could use the individual XCC connection options:
```
XCC-USERNAME=corb
XCC-PASSWORD=password@@@
XCC-HOSTNAME=localhost
XCC-PORT=8223
XCC-DBNAME=my-content-db
```

And it should work whether you happen to URLEncode the **XCC-PASSWORD** value or not.
