### ISSUE TITLE
Use CORB to run DataHub jobs

### ISSUE THREAD

**Issue by masyukun** [marklogic-community/corb2#89]
We have a client with a large cluster in AWS that has communication problems. DataHub Framework uses Data Movement SDK (DMSDK) to run batch jobs and is supposed to spread the load over all the nodes, but we are observing that it only uses the 1 node that the job was initiated on. 

Lots of problems running the harmonize job through a load balancer -- it just isn't working. So if we had an option to run a DataHub harmonize job with CORB as a fallback, it would really save the day.

I think what this would look like is some standard code replacing the main.sjs code. Possibly adapt NodeJS-reliant sjs code modules.

**Comment by hansenmc** [comment]
Are there any links to example main.sjs or NodeJS-reliant sjs code modules?

**Comment by bbandlamudi** [comment]
If it is possible to corbify your code into selector and transform, it is pretty straightforward to use corb's built-in load balancer which is supported in v2.4.*. Simply specify comma separated hostnames (IPs) or connection strings as part of connection configuration instead of single host or connection string.
