### ISSUE TITLE
Custom variables from PROCESS-MODULE not passed to POST-BATCH-MODULE

### ISSUE THREAD

**Issue by KetanDubey** [marklogic-community/corb2#93]
I was trying to pass  custom variable named "flag" from PROCESS-MODULE to POST-BATCH-MODULE. I have declared "flag" as string external variable in my PROCESS-MODULE  as well as POST-BATCH-MODULE Xquery module file.I am running CORB using gradle and have defined "flag" as external variable :
def flag=project.findProperty('indicator')
systemProperty "PROCESS-MODULE.flag", flag
systemProperty "POST-BATCH-MODULE.flag", flag.

Last line in PROCESS-MODULE xquery file--> return("POST-BATCH-MODULE.flag="||$flag)
Is there any other way to pass this "flag" variable set in PROCESS-MODULE to POST-BATCH-MODULE ?

**Comment by bbandlamudi** [comment]
You cannot pass custom variables from process-module to post-batch-module. You can only do it from the uris-module to other modules that follow. There will be many instances (often in millions) of process module executed by thread pool and corb cannot collect these custom variables from each of these process module instances and set it on a single instance of post-batch-module. Since iris-module is executed only once and same is true with post-batch-module, you can try to change move this logic to iris-module.

**Comment by KetanDubey** [comment]
> You cannot pass custom variables from process-module to post-batch-module. You can only do it from the uris-module to other modules that follow. There will be many instances (often in millions) of process module executed by thread pool and corb cannot collect these custom variables from each of these process module instances and set it on a single instance of post-batch-module. Since iris-module is executed only once and same is true with post-batch-module, you can try to change move this logic to iris-module.

Thanks for the information
